
output_path: "./output/upsnet/my_data"
model_prefix: "upsnet_resnet_50_cityscapes_"
symbol: resnet_50_upsnet
gpus: '0'
dataset:
  num_classes: 81
  num_seg_classes: 133
  dataset: mydata
  dataset_path: "./data/"
  image_set: train
  root_path: "./data/"
  test_image_set: val

network:
  has_rpn: true
  has_rcnn: true
  has_mask_head: true
  has_fcn_head: true
  fcn_head: "FCNHead"
  #fcn_num_layers: 2
  has_panoptic_head: true
  pretrained: "./model/pretrained_model/resnet-50-caffe.pth"


train:
  use_horovod: false
  scales:
  - 800
  max_size: 1333
  # solver
  display_iter: 20
  snapshot_step: 2000
  #resume: false
  resume: True
  #begin_iteration: 0
  begin_iteration: 504000
  #max_iteration: 360000
  max_iteration: 1440000
  decay_iteration:
      #- 240000
      #- 320000
  - 960000
  - 1280000
  warmup_iteration: 1500
  #lr: 0.005
  lr: 0.00125
  wd: 0.0001
  momentum: 0.9
  batch_size: 1

  fcn_loss_weight: 0.2
  fcn_with_roi_loss: true
  panoptic_loss_weight: 0.1
  panoptic_box_keep_fraction: 0.7

  eval_data: true

test:
  scales:
  - 800
  max_size: 1333
  batch_size: 1
  #test_iteration: 360000
  test_iteration: 1440000
  panoptic_stuff_area_limit: 4096
  vis_mask: True

